language: node_js

node_js:
  - "10"

cache:
  directories:
    - '$HOME/.sonar/cache'
    - 'node_modules'
    - 'coverage'

stages:
  - setup
  - audit
  - lint
  - test
  - sonar

jobs:
  include:
    - stage: setup
      script:
        - npm i
    - stage: audit
      script:
        - npm audit
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run coverage
    - stage: sonar
      script:
        - sonar-scanner
      addons:
        sonarcloud:
          token:
            secure: "$SONAR_API_KEY"
