language: node_js

node_js:
  - "10"

cache:
  directories:
    - '$HOME/.sonar/cache'
    - 'node_modules'
    - 'coverage'
    - 'build'

stages:
  - setup
#  - audit
#  - lint
#  - test
#  - sonar
  - build
  - deploy

jobs:
  include:
    - stage: setup
      script:
        - npm i
#    - stage: audit
#      script:
#        - npm audit
#    - stage: lint
#      script:
#        - npm run lint
#    - stage: test
#      script:
#        - npm run coverage
#    - stage: sonar
#      script:
#        - sonar-scanner
#      addons:
#        sonarcloud:
#          token:
#            secure: "$SONAR_API_KEY"
    - stage: build
      script:
        - npm run build
    - stage: deploy
      deploy:
        provider: lambda
        function_name: "event-scheduler"
        region: "eu-west-1"
        role: "arn:aws:iam::062883748514:role/service-role/time-based-event-scheduler-role-086pzy6k"
        handler_name: "handler"
        runtime: "nodejs10.0"
        zip: "./build/index.zip"
